/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_balsamiq_HelloBallDuktape_JavaModelWrapper */

#ifndef _Included_com_balsamiq_HelloBallDuktape_JavaModelWrapper
#define _Included_com_balsamiq_HelloBallDuktape_JavaModelWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_balsamiq_HelloBallDuktape_JavaModelWrapper
 * Method:    loadJS
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_balsamiq_HelloBallDuktape_JavaModelWrapper_loadJS
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_balsamiq_HelloBallDuktape_JavaModelWrapper
 * Method:    startModel
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_com_balsamiq_HelloBallDuktape_JavaModelWrapper_startModel
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     com_balsamiq_HelloBallDuktape_JavaModelWrapper
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_balsamiq_HelloBallDuktape_JavaModelWrapper_initialize
  (JNIEnv *, jobject);

/*
 * Class:     com_balsamiq_HelloBallDuktape_JavaModelWrapper
 * Method:    stopModel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_balsamiq_HelloBallDuktape_JavaModelWrapper_stopModel
  (JNIEnv *, jobject);

/*
 * Class:     com_balsamiq_HelloBallDuktape_JavaModelWrapper
 * Method:    onMouseDown
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_com_balsamiq_HelloBallDuktape_JavaModelWrapper_onMouseDown
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     com_balsamiq_HelloBallDuktape_JavaModelWrapper
 * Method:    onMouseUp
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_com_balsamiq_HelloBallDuktape_JavaModelWrapper_onMouseUp
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     com_balsamiq_HelloBallDuktape_JavaModelWrapper
 * Method:    onMouseMove
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_com_balsamiq_HelloBallDuktape_JavaModelWrapper_onMouseMove
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
