/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_balsamiq_HelloBall_JavaModelV8 */

#ifndef _Included_com_balsamiq_HelloBall_JavaModelV8
#define _Included_com_balsamiq_HelloBall_JavaModelV8
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_balsamiq_HelloBall_JavaModelV8
 * Method:    loadJS
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_balsamiq_HelloBall_JavaModelV8_loadJS
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_balsamiq_HelloBall_JavaModelV8
 * Method:    startModel
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_com_balsamiq_HelloBall_JavaModelV8_startModel
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     com_balsamiq_HelloBall_JavaModelV8
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_balsamiq_HelloBall_JavaModelV8_initialize
  (JNIEnv *, jobject);

/*
 * Class:     com_balsamiq_HelloBall_JavaModelV8
 * Method:    stopModel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_balsamiq_HelloBall_JavaModelV8_stopModel
  (JNIEnv *, jobject);

/*
 * Class:     com_balsamiq_HelloBall_JavaModelV8
 * Method:    onMouseDown
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_com_balsamiq_HelloBall_JavaModelV8_onMouseDown
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     com_balsamiq_HelloBall_JavaModelV8
 * Method:    onMouseUp
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_com_balsamiq_HelloBall_JavaModelV8_onMouseUp
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     com_balsamiq_HelloBall_JavaModelV8
 * Method:    onMouseMove
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_com_balsamiq_HelloBall_JavaModelV8_onMouseMove
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
